//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneId { get; set; }
        public string PhoneName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string CoverImage { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual NSX NSX { get; set; }
        public virtual Product Product { get; set; }
    }
}
